import type { Vertical, OrgNode } from '@/types'

export const SEED_VERTICALS: Vertical[] = [
  { id: 'hoichoi', name: 'Hoichoi', notes: '' },
  { id: 'hoichoi_bd', name: 'Hoichoi BD', notes: '' },
  { id: 'loglineai', name: 'LoglineAI', notes: '' },
  { id: 'sooper', name: 'Sooper', notes: '' },
]

export const SEED_NODES: OrgNode[] = [
  // ── Hoichoi ──────────────────────────────────────────────────────────
  { id:'ceo', vertical_id:'hoichoi', name:'Vishnu Mohta', desg:'Co-Founder & Executive Director', dept:'Management', res:'', parent_id:null, show_dept:false, acc:'#fa7d00', bg:null, txt:null, bdr:null, status:null },
  { id:'cht', vertical_id:'hoichoi', name:'Soumya Mukherjee', desg:'Chief Operating Officer - COO', dept:'Strategy & Revenue', res:'', parent_id:'ceo', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'cor', vertical_id:'hoichoi', name:'Salankara Biswas', desg:'GM - Content Marketing & Discovery', dept:'Content Marketing & Discovery', res:'', parent_id:'cht', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'caq', vertical_id:'hoichoi', name:'Sayantan Guha', desg:'GM - Brand Strategy', dept:'Brand & Communications', res:'', parent_id:'cht', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'cpt', vertical_id:'hoichoi', name:'Moloy Karmakar', desg:'GM - Product Operations', dept:'Technology', res:'', parent_id:'ceo', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'cto', vertical_id:'hoichoi', name:'Aloke Majumder', desg:'VP - Technology', dept:'Technology', res:'', parent_id:'ceo', show_dept:true, acc:null, bg:'#ec6a6a', txt:null, bdr:null, status:null },
  { id:'cgo', vertical_id:'hoichoi', name:'Shabinder Singh', desg:'Software Engineer', dept:'Technology', res:'', parent_id:'ceo', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'chr', vertical_id:'hoichoi', name:'Shirin Gupta', desg:'Head - Talent Acquisition', dept:'HR', res:'', parent_id:'ceo', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ls7bva8', vertical_id:'hoichoi', name:'Madhulata Agarwal', desg:'Consultant - Accounts & Finance', dept:'Accounts & Finance', res:'', parent_id:'ceo', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_3rnjnp4', vertical_id:'hoichoi', name:'Shreya Kaushik', desg:'Sr. Manager - Brand Alliances & Partnerships', dept:'Brand & Communications', res:'', parent_id:'cht', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_u1ip5k6', vertical_id:'hoichoi', name:'Sera Banerjee', desg:'Content Head - hoichoi', dept:'Content', res:'', parent_id:'cht', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_lw2mexf', vertical_id:'hoichoi', name:'Gunturu Sai Avinash', desg:'Sr. Manager - Performance Marketing', dept:'Acquisition & Retention', res:'', parent_id:'cht', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_peur9is', vertical_id:'hoichoi', name:'Rajib Biswas', desg:'VP - Post Production', dept:'Post Production', res:'', parent_id:'cht', show_dept:true, acc:null, bg:'#e68989', txt:null, bdr:null, status:null },
  { id:'_xr7s38w', vertical_id:'hoichoi', name:'Keerthana Anand', desg:'International Content Sales', dept:'International Licensing', res:'', parent_id:'cht', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_dxispxc', vertical_id:'hoichoi', name:'Sushim Ranjan Dutta', desg:'Manager - Talent Acquisition', dept:'HR', res:'', parent_id:'cht', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_e6lwkbj', vertical_id:'hoichoi', name:'Arnab Bhattacharjee', desg:'Manager - Promos', dept:'Audio-Visual', res:'', parent_id:'cor', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_geacxhw', vertical_id:'hoichoi', name:'Mangaldeep Karmakar', desg:'Asst. Manager - Motion Graphics', dept:'Audio-Visual', res:'', parent_id:'cor', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_0gnecoz', vertical_id:'hoichoi', name:'Ruchita Chatterji', desg:'Manager - Subtitles, S&P & Ops', dept:'Post Production', res:'', parent_id:'cor', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_hhjr1df', vertical_id:'hoichoi', name:'Ipsita Mukherjee', desg:'Assistant Manager - Content Operations', dept:'Content Marketing & Discovery', res:'', parent_id:'cor', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_1jlb5hj', vertical_id:'hoichoi', name:'Pritam Ghosh', desg:'Creative Content Producer', dept:'Content Marketing & Discovery', res:'', parent_id:'cor', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_wm8tc9e', vertical_id:'hoichoi', name:'Debmalya Mukherjee', desg:'Video Editor', dept:'Audio-Visual', res:'', parent_id:'_e6lwkbj', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_os8d9vk', vertical_id:'hoichoi', name:'Nitai Chand Das', desg:'Video Editor', dept:'Audio-Visual', res:'', parent_id:'_e6lwkbj', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_qa7wi1k', vertical_id:'hoichoi', name:'Arnab Neogi', desg:'Video Editor', dept:'Audio-Visual', res:'', parent_id:'_e6lwkbj', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_inq4v4l', vertical_id:'hoichoi', name:'Shakshi Das', desg:'Video Editor', dept:'Audio-Visual', res:'', parent_id:'_e6lwkbj', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_tn9mk2i', vertical_id:'hoichoi', name:'Sougata Bhowmick', desg:'Video Editor', dept:'Audio-Visual', res:'', parent_id:'_e6lwkbj', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_oongd1p', vertical_id:'hoichoi', name:'Sagnik Ghosh', desg:'Sr Executive - Graphics', dept:'Audio-Visual', res:'', parent_id:'_e6lwkbj', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_3nz1e16', vertical_id:'hoichoi', name:'Roshni Bose', desg:'Associate - Graphics', dept:'Audio-Visual', res:'', parent_id:'_oongd1p', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_7xhj0jq', vertical_id:'hoichoi', name:'Soumen Majumdar', desg:'Associate - Graphics', dept:'Audio-Visual', res:'', parent_id:'_oongd1p', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_uoxybjm', vertical_id:'hoichoi', name:'Ritika Das', desg:'Executive - Motion Graphics', dept:'Audio-Visual', res:'', parent_id:'_geacxhw', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_b35cdqr', vertical_id:'hoichoi', name:'Akancha Pipalwa', desg:'Associate - Content Operations (Hindi)', dept:'Post Production', res:'', parent_id:'_0gnecoz', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_bliy9k9', vertical_id:'hoichoi', name:'Swarnavo Banerjee', desg:'Associate - Creative Communications', dept:'Content Marketing & Discovery', res:'', parent_id:'_1jlb5hj', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_cn1ksyr', vertical_id:'hoichoi', name:'Soumita Sarkar', desg:'PR + Production', dept:'Content Marketing & Discovery', res:'', parent_id:'_1jlb5hj', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_iqepihn', vertical_id:'hoichoi', name:'Anurag Ghosh', desg:'Asst. Manager - Marketing', dept:'Brand & Communications', res:'', parent_id:'caq', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_iqdofhz', vertical_id:'hoichoi', name:'Sreemoyee Banerjee', desg:'Executive Producer', dept:'Brand & Communications', res:'', parent_id:'caq', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_wpk51xq', vertical_id:'hoichoi', name:'Debanjan Dasgupta', desg:'Sr. Executive - Social Media', dept:'Social Media', res:'', parent_id:'caq', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ibmmzhd', vertical_id:'hoichoi', name:'Ishani Bose', desg:'Sr. Executive - Social Media', dept:'Social Media', res:'', parent_id:'caq', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_u4jpntf', vertical_id:'hoichoi', name:'Amrita Kundu', desg:'Associate - Social Media', dept:'Social Media', res:'', parent_id:'caq', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_iplakkm', vertical_id:'hoichoi', name:'Diptesh Bhattacharya', desg:'Asst. Manager - Creative Solutions', dept:'Brand & Communications', res:'', parent_id:'_3rnjnp4', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ugwi2zo', vertical_id:'hoichoi', name:'Disha Roy', desg:'Associate - Brand Partnerships', dept:'Brand & Communications', res:'', parent_id:'_3rnjnp4', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_n3bkczp', vertical_id:'hoichoi', name:'Geetopriya Saha', desg:'Management Trainee - Brand Solutions', dept:'Brand & Communications', res:'', parent_id:'_3rnjnp4', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_exqk1l6', vertical_id:'hoichoi', name:'Sreya Dutta', desg:'Associate - Content', dept:'Content', res:'', parent_id:'_u1ip5k6', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_3c0fe7r', vertical_id:'hoichoi', name:'Sarthak Das Sharma', desg:'Creative Producer', dept:'Content', res:'', parent_id:'_u1ip5k6', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_fxhti51', vertical_id:'hoichoi', name:'Saptarshi Majumdar', desg:'Senior Executive Producer', dept:'Content', res:'', parent_id:'_u1ip5k6', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_0gss1a5', vertical_id:'hoichoi', name:'Pronay Roy', desg:'Asst Manager - Digital Marketing', dept:'Acquisition & Retention', res:'', parent_id:'_lw2mexf', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_t05ft8x', vertical_id:'hoichoi', name:'Anirban Jana', desg:'Asst Manager - Digital Marketing', dept:'Acquisition & Retention', res:'', parent_id:'_lw2mexf', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_gh6879g', vertical_id:'hoichoi', name:'Katib Khan', desg:'Senior Associate - Performance Marketing', dept:'Acquisition & Retention', res:'', parent_id:'_lw2mexf', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_7r869hs', vertical_id:'hoichoi', name:'Soumi Banerjee', desg:'Associate - CRM', dept:'Acquisition & Retention', res:'', parent_id:'_lw2mexf', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_4txa3su', vertical_id:'hoichoi', name:'Sourav Ghosh', desg:'Manager - Post Production', dept:'Post Production', res:'', parent_id:'_peur9is', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_0v8cv8y', vertical_id:'hoichoi', name:'Amit Kumar', desg:'Senior DI Colorist', dept:'Post Production', res:'', parent_id:'_peur9is', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_c3nppcm', vertical_id:'hoichoi', name:'Satyajit Maji', desg:'Executive - Post Production', dept:'Post Production', res:'', parent_id:'_4txa3su', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ofu4hb4', vertical_id:'hoichoi', name:'Binay Bhowmick', desg:'Sr. Associate - Post Production', dept:'Post Production', res:'', parent_id:'_4txa3su', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_718rbwe', vertical_id:'hoichoi', name:'Preeti Mondal', desg:'Associate - Employee Experience', dept:'HR', res:'', parent_id:'_dxispxc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ogm5uyp', vertical_id:'hoichoi', name:'Sayantan Raha', desg:'Manager - Customer Experience & Quality Control', dept:'Customer Support', res:'', parent_id:'cpt', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_4bbrcgz', vertical_id:'hoichoi', name:'Avinash Singh', desg:'Sr. Software Engineer', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_x12fkau', vertical_id:'hoichoi', name:'Sayandeep Dey', desg:'Fullstack Developer', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_fkhce5l', vertical_id:'hoichoi', name:'Avijit Sen', desg:'Fullstack Developer', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_z02xclm', vertical_id:'hoichoi', name:'Gaurav Tyagi', desg:'Android Developer', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_u0wpe6u', vertical_id:'hoichoi', name:'Poulastaa Das', desg:'Android Developer', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_babp8g1', vertical_id:'hoichoi', name:'Kapil Jain', desg:'QA', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ojispbd', vertical_id:'hoichoi', name:'Sandipan Mondal', desg:'Manager - Tech & Content Ops', dept:'Technology', res:'', parent_id:'cto', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_3m2g3ry', vertical_id:'hoichoi', name:'Shubhajit Halder', desg:'Python Developer', dept:'Technology', res:'', parent_id:'_ojispbd', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_re2l9ey', vertical_id:'hoichoi', name:'Sujit Sen', desg:'Manager - Accounts', dept:'Accounts & Finance', res:'', parent_id:'_ls7bva8', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_d0id52h', vertical_id:'hoichoi', name:'Honey Agarwal', desg:'Asst. Manager - Accounts', dept:'Accounts & Finance', res:'', parent_id:'_ls7bva8', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_r0hrlf8', vertical_id:'hoichoi', name:'Sanjoy Das', desg:'Executive - Accounts', dept:'Accounts & Finance', res:'', parent_id:'_ls7bva8', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_k0hdyqs', vertical_id:'hoichoi', name:'Senior Associate - Social Media Marketing', desg:'(new hire)', dept:'Content Marketing & Discovery', res:'joining due 4th May 2026', parent_id:'cor', show_dept:true, acc:'#000000', bg:'#fbff00', txt:null, bdr:'#000000', status:null },
  { id:'_7qoyte4', vertical_id:'hoichoi', name:'Retention - mid/sr resource', desg:'', dept:'Acquisition & Retention', res:'(to hire)', parent_id:'_lw2mexf', show_dept:true, acc:'#000000', bg:'#fff700', txt:null, bdr:'#000000', status:null },
  { id:'_815jrkh', vertical_id:'hoichoi', name:'Data Analyst', desg:'mid', dept:'Acquisition & Retention', res:'(to hire)', parent_id:'_lw2mexf', show_dept:true, acc:'#000000', bg:'#fbff00', txt:'#000000', bdr:'#000000', status:null },
  { id:'_bscc5ak', vertical_id:'hoichoi', name:'Product Designer', desg:'mid/sr', dept:'Technology', res:'(TO HIRE)', parent_id:'cpt', show_dept:true, acc:'#000000', bg:'#fff700', txt:'#000000', bdr:'#000000', status:null },
  { id:'_n18yjfv', vertical_id:'hoichoi', name:'Boloram Mitra', desg:'Team Lead - CX & QA', dept:'Customer Support', res:'', parent_id:'_ogm5uyp', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_y90fs4k', vertical_id:'hoichoi', name:'Nikhita Chatterjee', desg:'Executive - Customer Support', dept:'Customer Support', res:'', parent_id:'_ogm5uyp', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_6tqlvnr', vertical_id:'hoichoi', name:'Debayani Panigrahi', desg:'Associate - Customer Support', dept:'Customer Support', res:'', parent_id:'_ogm5uyp', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_toomxss', vertical_id:'hoichoi', name:'Saswati Mitra', desg:'Executive - Customer Support', dept:'Customer Support', res:'', parent_id:'_ogm5uyp', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_4wpguku', vertical_id:'hoichoi', name:'Outbound - CS (6 agents)', desg:'Suchetana, Sneha, Sourav, Paromita, Aritra, Aman', dept:'Customer Support', res:'', parent_id:'_ogm5uyp', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_4yqjarx', vertical_id:'hoichoi', name:'Preeti Gandhi', desg:'Legal Consultant', dept:'Legal', res:'', parent_id:'ceo', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_7ocm6xg', vertical_id:'hoichoi', name:'Medha Mukherjee', desg:'Associate - Legal', dept:'Legal', res:'', parent_id:'_4yqjarx', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_m712jtt', vertical_id:'hoichoi', name:'Fullstack (Backend) Developer', desg:'Jr/Mid (to hire)', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:'#000000', bg:'#fff700', txt:null, bdr:null, status:null },
  { id:'_exsh6cw', vertical_id:'hoichoi', name:'Fullstack (Backend) Developer', desg:'Jr/Mid (to hire)', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:'#000000', bg:'#fff700', txt:null, bdr:null, status:null },
  { id:'_wgp0j05', vertical_id:'hoichoi', name:'KMP + Compose UI', desg:'Jr/Mid (to hire)', dept:'Technology', res:'', parent_id:'cpt', show_dept:true, acc:'#000000', bg:'#fff700', txt:null, bdr:null, status:null },
  // ── Hoichoi BD ─────────────────────────────────────────────────────
  { id:'bh', vertical_id:'hoichoi_bd', name:'Sakib Ur Rahman', desg:'Business Lead - Bangladesh', dept:'Strategy & Revenue', res:'', parent_id:null, show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'bcm', vertical_id:'hoichoi_bd', name:'Tanzina Rahman', desg:'Manager - PR & Communications', dept:'PR', res:'', parent_id:'bh', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'bgm', vertical_id:'hoichoi_bd', name:'S M Nazmul Nayan', desg:'Executive Producer', dept:'Content', res:'BD market', parent_id:'bh', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'btm', vertical_id:'hoichoi_bd', name:'Md Imam Hossain Roni', desg:'Asst Manager - Customer Support', dept:'Customer Support', res:'Reporting to Sayantan Raha', parent_id:null, show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_2pudyn1', vertical_id:'hoichoi_bd', name:'Florence Mithua D Cruze', desg:'Sr. Executive - Customer Support', dept:'Customer Support', res:'', parent_id:'btm', show_dept:true, acc:null, bg:'#ff7070', txt:'#000000', bdr:'#c73333', status:null },
  // ── LoglineAI ───────────────────────────────────────────────────────
  { id:'lc', vertical_id:'loglineai', name:'Mandar Banerjee', desg:'AV - Head', dept:'LoglineAI', res:'', parent_id:null, show_dept:false, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'lcd', vertical_id:'loglineai', name:'Shaket Banerjee', desg:'Creative Director - AI', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_o4im31s', vertical_id:'loglineai', name:'Pratik Banerjee', desg:'Video Editor', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_g0ge07r', vertical_id:'loglineai', name:'Aayush Kumar', desg:'Fullstack Engineer - AI', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_twwcjm5', vertical_id:'loglineai', name:'Burhanuddin Kherodawala', desg:'AI Engineer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_pb9n1fa', vertical_id:'loglineai', name:'Ashish Mallick', desg:'Sr. AI Artist', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_l0e8mxf', vertical_id:'loglineai', name:'Anwesha Debnath', desg:'Sr AI Artist', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ofd2asg', vertical_id:'loglineai', name:'Sayan Maiti', desg:'Sr AI Artist', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_icdt1p5', vertical_id:'loglineai', name:'Shinjini Nandy', desg:'Sr AI Artist', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_zcbwrnk', vertical_id:'loglineai', name:'Gaurav Kuri', desg:'Associate Creative Director - AI', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_horqsfb', vertical_id:'loglineai', name:'Sarani Deb', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_12v3b4j', vertical_id:'loglineai', name:'Shantuno Chakraborty', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_o6srft0', vertical_id:'loglineai', name:'Shreya Paul', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_wqs2b3i', vertical_id:'loglineai', name:'Sumona Mondal', desg:'Video Editor', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_y9idlmf', vertical_id:'loglineai', name:'Kaustav Das', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_rdp0zlh', vertical_id:'loglineai', name:'Soumoyajit Dey', desg:'Video Editor', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_1pnlyzl', vertical_id:'loglineai', name:'Aritra Mondal', desg:'Video Editor', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_a14akdg', vertical_id:'loglineai', name:'Sohom Chatterjee', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_u1alvsq', vertical_id:'loglineai', name:'Somdatta Biswas', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_l6ea7xn', vertical_id:'loglineai', name:'Aniket Ray', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_c4g2ze7', vertical_id:'loglineai', name:'Bhavya Nagpal', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_7i0phjw', vertical_id:'loglineai', name:'Utsav Dutta', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ehqog3l', vertical_id:'loglineai', name:'Manab Kundu', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ptdddso', vertical_id:'loglineai', name:'Debarghya Mandal', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_d8bmwl5', vertical_id:'loglineai', name:'Mohit Mandawat', desg:'AI Engineer', dept:'LoglineAI', res:'Part-time / hourly', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_df3zrfq', vertical_id:'loglineai', name:'Samata Sinha', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_pglu8g7', vertical_id:'loglineai', name:'Manashi Mondal', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_ueaw7nf', vertical_id:'loglineai', name:'Agnibha Ghosh Dastidar', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_o49nbs0', vertical_id:'loglineai', name:'Payel Sanyal', desg:'Gen AI Promo Producer', dept:'LoglineAI', res:'', parent_id:'lc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  // ── Sooper ──────────────────────────────────────────────────────────
  { id:'sc', vertical_id:'sooper', name:'Sambbhav Khettrapal', desg:'Head - Microdramas', dept:'Sooper', res:'', parent_id:null, show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'sch', vertical_id:'sooper', name:'Shoham Banerjee', desg:'Creative Executive Producer', dept:'Sooper', res:'', parent_id:'sc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_uwlccao', vertical_id:'sooper', name:'Adhidev Mukherjee', desg:'Content Head - New Formats', dept:'Sooper', res:'', parent_id:null, show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_fd04uuo', vertical_id:'sooper', name:'Sumit Rani', desg:'Writer', dept:'Sooper', res:'', parent_id:'sc', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_pdyjd1i', vertical_id:'sooper', name:'Saswati Sinha', desg:'Content Producer - New Formats', dept:'Sooper', res:'', parent_id:'_uwlccao', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_d6bbtls', vertical_id:'sooper', name:'Abhijan Chakraborty', desg:'Content Producer - New Formats', dept:'Sooper', res:'', parent_id:'_uwlccao', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_5x87mtq', vertical_id:'sooper', name:'Rithuparna Ghosh', desg:'Content Producer - New Formats', dept:'Sooper', res:'', parent_id:'_uwlccao', show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
  { id:'_4v8pf7l', vertical_id:'sooper', name:'Updesh', desg:'Sr Promo Producer', dept:'Sooper', res:'reporting to Mandar Banerjee', parent_id:null, show_dept:true, acc:null, bg:null, txt:null, bdr:null, status:null },
]
